/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package agenda;

import javax.swing.JOptionPane;

/**
 *
 * @author ar316b
 */
public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    Cliente cliente1 = new Cliente("arnold", "100", "ahorros", 0);
    public Gui() {
        initComponents();
        this.setSize(240, 300);
        this.setTitle("banco de prueba");
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        btnretiro = new javax.swing.JButton();
        btnAgregarCliente = new javax.swing.JButton();
        btnMostrar = new javax.swing.JButton();
        btndeposito = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Noto Sans", 1, 18)); // NOI18N
        jLabel4.setText("BANCO UT");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, -1));

        btnretiro.setText("Realizar retiro");
        btnretiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnretiroActionPerformed(evt);
            }
        });
        getContentPane().add(btnretiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 180, 150, -1));

        btnAgregarCliente.setText("Agregar cliente");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregarCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        btnMostrar.setText("Mostrar Info cliente");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnMostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        btndeposito.setText("Realizar deposito");
        btndeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndepositoActionPerformed(evt);
            }
        });
        getContentPane().add(btndeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 140, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnretiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnretiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnretiroActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        // TODO add your handling code here:
        
        String nombre = JOptionPane.showInputDialog(this, "ingrese el nombre del cliente");
        String Ncuenta = JOptionPane.showInputDialog(this, "ingrese el numero de cuenta");
        String tipoCuenta = JOptionPane.showInputDialog(this, "ingrese el tipo de cuenta");
        String balance = JOptionPane.showInputDialog(this, "ingrese el balance del cliente");
        double monto = Double.parseDouble(balance);
       
       JOptionPane.showConfirmDialog(this,"cuenta agregada");
        
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(rootPane, cliente1.mostrarInfo());
        
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btndepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndepositoActionPerformed
        // TODO add your handling code here:
        String monto  = JOptionPane.showInputDialog(this, "ingrese la cantidad del deposito");
        if(!cliente1.isDouble(monto)){
            JOptionPane.showMessageDialog(rootPane, "no se se puede ingresar valores nonumericos");
        }else{
        double amount = Double.parseDouble(monto);
        cliente1.credito(amount);
        }
    }//GEN-LAST:event_btndepositoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btndeposito;
    private javax.swing.JButton btnretiro;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
